transformer:
  encoder_layer: 6
  encoder_head: 2
  encoder_hidden: 256
  generator_layr: 4
  decoder_layer: 2
  decoder_head: 2
  decoder_hidden: 256
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.2
  decoder_dropout: 0.2

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5

variance_embedding:
  pitch_quantization: "linear" 
  energy_quantization: "linear" 
  n_bins: 256

multi_speaker: True
temperature: 0.0005

max_seq_len: 2048

vocoder:
  model: "HiFi-GAN" 
  speaker: "universal" 
  config_path: "/home/work/source-filter-FastSpeech2/hifigan/config.json"
  ljspeech_path: "/home/work/source-filter-FastSpeech2/hifigan/generator_LJSpeech.pth.tar"
  universal_path: "/home/work/source-filter-FastSpeech2/hifigan/generator_universal.pth.tar"
