dataset: "kss"

path:
  corpus_path: "/home/work/source-filter-FastSpeech2/kss"
  raw_path: "/home/work/source-filter-FastSpeech2/kss/transcript.v.1.4.txt"
  preprocessed_path: "./preprocessed_data/kss"
  training_files: "./preprocessed_data/kss/train.txt"
  validation_files: "./preprocessed_data/kss/val.txt"

preprocessing:
  val_size: 512
  duration:
    beta_binomial_scaling_factor: 1
  text:
    text_cleaners: ["korean_cleaners"]
    language: "ko"
    use_intersperse: True
  audio:
    trim_top_db: 35
    trim_frame_length: 4096
    trim_hop_length: 256
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "frame_level" 
    normalization: True
